const express = require("express");
const dotenv = require("dotenv").config();
const cors = require("cors");
const { errorHandler } = require("./middleware/errorMiddleware");
const connectDB = require("./config/db");
const port = process.env.PORT || 5000;
const path = require("path"); // we need the path module from node in order to give back access to frontend react app (line27)
const res = require("express/lib/response");

const app = express();

//CORS is a necessary security mechanism that allows a web page from one domain or Origin to access a resource with a different domain
app.use(cors());
app.use(express.json({ limit: 1024 * 1024 * 4 })); //this tells express: anything that comes in as body, convert it to json. We increased file limit to allow for image uploads

app.use(express.urlencoded({ extended: false }));

app.use("/api/users", require("./routes/userRoutes"));
app.use("/api/conversations", require("./routes/conversationRoutes"));
app.use("/api/messages", require("./routes/messageRoutes"));

app.use(errorHandler);

// Deployment. In order for our Heroku server to serve our react app, we must do this:
if (process.env.NODE_ENV === "production") {
  //middleware that gives our server, access to our frontend react app:
  app.use(express.static(path.join(__dirname, "../client/build")));
  // whenever we reach any(*) get route on our app, we want to send the data from the index.html file to our frontend when our app is successfully running
  app.get("*", (req, res) => {
    res.sendFile(path.join(__dirname, "../client", "build", "index.html")); //index.html with the build folder (generated by the 'yarn run build' command which runs 'react-scripts build') contains the minified code for our app
  });
} else {
  app.get("/", (req, res) => {
    res.send("Api running");
  });
}

app.listen(port, () => {
  // starts the server and listens on the port
  connectDB();
  console.log(`Server started on port ${port}`);
});
